// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzePitch(arg1:string,arg2:string):Promise<main.PitchResult>;

export function ConvertBatch(arg1:Array<main.FileInfo>,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<Array<main.ConvertResult>>;

export function ConvertFile(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<main.ConvertResult>;

export function GetDetectors():Promise<Array<string>>;

export function GetSupportedFormats():Promise<Array<string>>;

export function SelectFiles():Promise<Array<main.FileInfo>>;

export function SelectFolder():Promise<string>;
