// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePitch(arg1, arg2) {
  return window['go']['main']['App']['AnalyzePitch'](arg1, arg2);
}

export function ConvertBatch(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConvertBatch'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ConvertFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDetectors() {
  return window['go']['main']['App']['GetDetectors']();
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
